// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/message/internal/handler"
	"flamingo/app/message/internal/repository"
	"flamingo/app/message/internal/server"
	"flamingo/app/message/internal/service"
	"flamingo/pkg/broker"
	"flamingo/pkg/cache"
	"flamingo/pkg/config"
	"flamingo/pkg/database"
	"flamingo/pkg/grpc"
	"flamingo/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bc config.Bootstrap, tc config.Typing) (*kratos.App, func(), error) {
	configServer := bc.Server
	auth := bc.Auth
	data := bc.Data
	configDatabase := data.Database
	db, cleanup, err := database.NewDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	messageRepository := repository.NewMessageRepository(db, logger)
	readReceiptRepository := repository.NewReadReceiptRepository(db, logger)
	sequenceRepository := repository.NewSequenceRepository(db, logger)
	sendIdempotencyRepository := repository.NewSendIdempotencyRepository(db, logger)
	configCache := data.Cache
	cacheCache, cleanup2, err := cache.NewCache(configCache)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	typingRepository := repository.NewTypingRepository(cacheCache, logger)
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	conversationServiceClient := grpc.NewConversationServiceClient(consulRegistry)
	friendServiceClient := grpc.NewFriendServiceClient(consulRegistry)
	groupServiceClient := grpc.NewGroupServiceClient(consulRegistry)
	configBroker := data.Broker
	brokerBroker, cleanup3, err := broker.NewBroker(configBroker)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	messageService := service.NewMessageService(tc, messageRepository, readReceiptRepository, sequenceRepository, sendIdempotencyRepository, typingRepository, conversationServiceClient, friendServiceClient, groupServiceClient, brokerBroker, db, logger)
	messageHandler := handler.NewMessageHandler(messageService, logger)
	grpcServer := server.NewGRPCServer(configServer, auth, logger, messageHandler)
	httpServer := server.NewHTTPServer(configServer)
	lifecycle, cleanup4, err := service.NewMessageLifecycle(logger, messageRepository, brokerBroker)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
