// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/user/internal/handler"
	"flamingo/app/user/internal/repository"
	"flamingo/app/user/internal/server"
	"flamingo/app/user/internal/service"
	"flamingo/pkg/app"
	"flamingo/pkg/auth"
	"flamingo/pkg/broker"
	"flamingo/pkg/cache"
	"flamingo/pkg/config"
	"flamingo/pkg/database"
	"flamingo/pkg/grpc"
	"flamingo/pkg/registry"
	"flamingo/pkg/sender"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bc config.Bootstrap, vc config.Verify) (*kratos.App, func(), error) {
	configServer := bc.Server
	configAuth := bc.Auth
	data := bc.Data
	configDatabase := data.Database
	db, cleanup, err := database.NewDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	userProfileRepository := repository.NewUserProfileRepository(db, logger)
	userSettingsRepository := repository.NewUserSettingsRepository(db, logger)
	userQRCodeRepository := repository.NewUserQRCodeRepository(db, logger)
	userPushTokenRepository := repository.NewUserPushTokenRepository(db, logger)
	userRepository := repository.NewUserRepository(db, logger)
	userDeviceRepository := repository.NewUserDeviceRepository(db, logger)
	userSessionRepository := repository.NewUserSessionRepository(db, logger)
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	friendServiceClient := grpc.NewFriendServiceClient(consulRegistry)
	environment := bc.Environment
	verificationCodeRepository := repository.NewVerificationCodeRepository(db, logger)
	verificationTemplateRepository := repository.NewVerificationTemplateRepository(db, logger)
	configCache := data.Cache
	cacheCache, cleanup2, err := cache.NewCache(configCache)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	smsSender := sender.NewNoopSMSSender()
	email := vc.Email
	emailSender, err := sender.NewEmailSender(email)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	verificationManager := service.NewVerificationManager(logger, vc, environment, verificationCodeRepository, verificationTemplateRepository, cacheCache, smsSender, emailSender)
	jwtManager, err := auth.NewJWTManager(configAuth)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	configBroker := data.Broker
	brokerBroker, cleanup3, err := broker.NewBroker(configBroker)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userService := service.NewUserService(db, configAuth, userProfileRepository, userSettingsRepository, userQRCodeRepository, userPushTokenRepository, userRepository, userDeviceRepository, userSessionRepository, friendServiceClient, verificationManager, jwtManager, brokerBroker, logger)
	userHandler := handler.NewUserHandler(userService, logger)
	grpcServer := server.NewGRPCServer(configServer, configAuth, logger, userHandler)
	httpServer := server.NewHTTPServer(configServer)
	lifecycle := app.DefaultLifecycle()
	kratosApp := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return kratosApp, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
