// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/file/internal/handler"
	"flamingo/app/file/internal/repository"
	"flamingo/app/file/internal/server"
	"flamingo/app/file/internal/service"
	"flamingo/pkg/app"
	"flamingo/pkg/config"
	"flamingo/pkg/database"
	"flamingo/pkg/oss"
	"flamingo/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bc config.Bootstrap, mc config.Minio) (*kratos.App, func(), error) {
	configServer := bc.Server
	auth := bc.Auth
	data := bc.Data
	configDatabase := data.Database
	db, cleanup, err := database.NewDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	fileRepository := repository.NewFileRepository(db, logger)
	minioClient, err := oss.NewMinioClient(mc)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	fileService := service.NewFileService(fileRepository, minioClient, db, logger)
	fileHandler := handler.NewFileHandler(fileService, logger)
	grpcServer := server.NewGRPCServer(configServer, auth, logger, fileHandler)
	httpServer := server.NewHTTPServer(configServer)
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	lifecycle := app.DefaultLifecycle()
	kratosApp := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return kratosApp, func() {
		cleanup()
	}, nil
}
