// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/realtime/internal/handler"
	"flamingo/app/realtime/internal/server"
	"flamingo/app/realtime/internal/service"
	"flamingo/pkg/app"
	"flamingo/pkg/auth"
	"flamingo/pkg/broker"
	"flamingo/pkg/config"
	"flamingo/pkg/grpc"
	"flamingo/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bc config.Bootstrap) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer()
	configServer := bc.Server
	configAuth := bc.Auth
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	userServiceClient := grpc.NewUserServiceClient(consulRegistry)
	friendServiceClient := grpc.NewFriendServiceClient(consulRegistry)
	groupServiceClient := grpc.NewGroupServiceClient(consulRegistry)
	fileServiceClient := grpc.NewFileServiceClient(consulRegistry)
	messageServiceClient := grpc.NewMessageServiceClient(consulRegistry)
	conversationServiceClient := grpc.NewConversationServiceClient(consulRegistry)
	rtcServiceClient := grpc.NewRtcServiceClient(consulRegistry)
	pushServiceClient := grpc.NewPushServiceClient(consulRegistry)
	jwtManager, err := auth.NewJWTManager(configAuth)
	if err != nil {
		return nil, nil, err
	}
	connectionManager := handler.NewConnectionManager(logger)
	data := bc.Data
	configBroker := data.Broker
	brokerBroker, cleanup, err := broker.NewBroker(configBroker)
	if err != nil {
		return nil, nil, err
	}
	subscriber := service.NewNotificationSubscriber(logger, brokerBroker, connectionManager)
	webSocketHandler := handler.NewWebSocketHandler(logger, userServiceClient, friendServiceClient, groupServiceClient, fileServiceClient, messageServiceClient, conversationServiceClient, rtcServiceClient, pushServiceClient, jwtManager, connectionManager, subscriber)
	httpServer := server.NewHTTPServer(configServer, configAuth, logger, webSocketHandler)
	lifecycle := app.DefaultLifecycle()
	kratosApp := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return kratosApp, func() {
		cleanup()
	}, nil
}
