// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/rtc/internal/handler"
	"flamingo/app/rtc/internal/repository"
	"flamingo/app/rtc/internal/server"
	"flamingo/app/rtc/internal/service"
	"flamingo/pkg/app"
	"flamingo/pkg/broker"
	"flamingo/pkg/config"
	"flamingo/pkg/database"
	"flamingo/pkg/grpc"
	"flamingo/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bc config.Bootstrap, lc config.Livekit) (*kratos.App, func(), error) {
	configServer := bc.Server
	auth := bc.Auth
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	friendServiceClient := grpc.NewFriendServiceClient(consulRegistry)
	data := bc.Data
	configDatabase := data.Database
	db, cleanup, err := database.NewDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	callRepository := repository.NewCallRepository(db, logger)
	meetingRepository := repository.NewMeetingRepository(db, logger)
	configBroker := data.Broker
	brokerBroker, cleanup2, err := broker.NewBroker(configBroker)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rtcService := service.NewRtcService(lc, friendServiceClient, callRepository, meetingRepository, brokerBroker, logger)
	rtcHandler := handler.NewRtcHandler(rtcService, logger)
	grpcServer := server.NewGRPCServer(configServer, auth, logger, rtcHandler)
	httpServer := server.NewHTTPServer(configServer)
	lifecycle := app.DefaultLifecycle()
	kratosApp := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
