// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/friend/internal/handler"
	"flamingo/app/friend/internal/repository"
	"flamingo/app/friend/internal/server"
	"flamingo/app/friend/internal/service"
	"flamingo/pkg/app"
	"flamingo/pkg/broker"
	"flamingo/pkg/config"
	"flamingo/pkg/database"
	"flamingo/pkg/grpc"
	"flamingo/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bc config.Bootstrap) (*kratos.App, func(), error) {
	configServer := bc.Server
	auth := bc.Auth
	data := bc.Data
	configDatabase := data.Database
	db, cleanup, err := database.NewDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	friendshipRepository := repository.NewFriendshipRepository(db, logger)
	friendRequestRepository := repository.NewFriendRequestRepository(db, logger)
	blacklistRepository := repository.NewBlacklistRepository(db, logger)
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	userServiceClient := grpc.NewUserServiceClient(consulRegistry)
	conversationServiceClient := grpc.NewConversationServiceClient(consulRegistry)
	configBroker := data.Broker
	brokerBroker, cleanup2, err := broker.NewBroker(configBroker)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	friendService := service.NewFriendService(friendshipRepository, friendRequestRepository, blacklistRepository, userServiceClient, conversationServiceClient, brokerBroker, db, logger)
	friendHandler := handler.NewFriendHandler(friendService, logger)
	grpcServer := server.NewGRPCServer(configServer, auth, logger, friendHandler)
	httpServer := server.NewHTTPServer(configServer)
	lifecycle := app.DefaultLifecycle()
	kratosApp := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
