// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/gateway/internal/handler"
	"flamingo/app/gateway/internal/server"
	"flamingo/pkg/app"
	"flamingo/pkg/config"
	"flamingo/pkg/grpc"
	"flamingo/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp initializes the gateway Kratos application via Wire.
func initApp(logger log.Logger, bc config.Bootstrap) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer()
	configServer := bc.Server
	auth := bc.Auth
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	userServiceClient := grpc.NewUserServiceClient(consulRegistry)
	userServiceHTTPServer := handler.NewUserProxy(userServiceClient)
	friendServiceClient := grpc.NewFriendServiceClient(consulRegistry)
	friendServiceHTTPServer := handler.NewFriendProxy(friendServiceClient)
	groupServiceClient := grpc.NewGroupServiceClient(consulRegistry)
	groupServiceHTTPServer := handler.NewGroupProxy(groupServiceClient)
	conversationServiceClient := grpc.NewConversationServiceClient(consulRegistry)
	conversationServiceHTTPServer := handler.NewConversationProxy(conversationServiceClient)
	messageServiceClient := grpc.NewMessageServiceClient(consulRegistry)
	messageServiceHTTPServer := handler.NewMessageProxy(messageServiceClient)
	fileServiceClient := grpc.NewFileServiceClient(consulRegistry)
	fileServiceHTTPServer := handler.NewFileProxy(fileServiceClient)
	httpServer := server.NewHTTPServer(configServer, auth, logger, userServiceHTTPServer, friendServiceHTTPServer, groupServiceHTTPServer, conversationServiceHTTPServer, messageServiceHTTPServer, fileServiceHTTPServer)
	lifecycle := app.DefaultLifecycle()
	kratosApp := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return kratosApp, func() {
	}, nil
}
