// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/push/internal/handler"
	"flamingo/app/push/internal/repository"
	"flamingo/app/push/internal/server"
	"flamingo/app/push/internal/service"
	"flamingo/pkg/broker"
	"flamingo/pkg/config"
	"flamingo/pkg/database"
	"flamingo/pkg/jpush"
	"flamingo/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bc config.Bootstrap, tc config.JPush) (*kratos.App, func(), error) {
	configServer := bc.Server
	auth := bc.Auth
	data := bc.Data
	configDatabase := data.Database
	db, cleanup, err := database.NewDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	pushLogRepository := repository.NewPushLogRepository(db, logger)
	environment := bc.Environment
	client := jpush.NewClient(environment, tc)
	pushService := service.NewPushService(pushLogRepository, client, logger)
	pushHandler := handler.NewPushHandler(pushService, logger)
	grpcServer := server.NewGRPCServer(configServer, auth, logger, pushHandler)
	httpServer := server.NewHTTPServer(configServer)
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	configBroker := data.Broker
	brokerBroker, cleanup2, err := broker.NewBroker(configBroker)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	lifecycle := service.NewPushLifecycle(brokerBroker, pushService, logger)
	app := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
