// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/conversation/internal/handler"
	"flamingo/app/conversation/internal/repository"
	"flamingo/app/conversation/internal/server"
	"flamingo/app/conversation/internal/service"
	"flamingo/pkg/app"
	"flamingo/pkg/broker"
	"flamingo/pkg/config"
	"flamingo/pkg/database"
	"flamingo/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bc config.Bootstrap) (*kratos.App, func(), error) {
	configServer := bc.Server
	auth := bc.Auth
	data := bc.Data
	configDatabase := data.Database
	db, cleanup, err := database.NewDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	conversationRepository := repository.NewConversationRepository(db, logger)
	configBroker := data.Broker
	brokerBroker, cleanup2, err := broker.NewBroker(configBroker)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	conversationService := service.NewConversationService(conversationRepository, brokerBroker, logger)
	conversationHandler := handler.NewConversationHandler(conversationService, logger)
	grpcServer := server.NewGRPCServer(configServer, auth, logger, conversationHandler)
	httpServer := server.NewHTTPServer(configServer)
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	lifecycle := app.DefaultLifecycle()
	kratosApp := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
