// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flamingo/app/group/internal/handler"
	"flamingo/app/group/internal/repository"
	"flamingo/app/group/internal/server"
	"flamingo/app/group/internal/service"
	"flamingo/pkg/app"
	"flamingo/pkg/broker"
	"flamingo/pkg/config"
	"flamingo/pkg/database"
	"flamingo/pkg/grpc"
	"flamingo/pkg/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(logger log.Logger, bc config.Bootstrap) (*kratos.App, func(), error) {
	configServer := bc.Server
	auth := bc.Auth
	data := bc.Data
	configDatabase := data.Database
	db, cleanup, err := database.NewDB(configDatabase)
	if err != nil {
		return nil, nil, err
	}
	groupRepository := repository.NewGroupRepository(db, logger)
	groupMemberRepository := repository.NewGroupMemberRepository(db, logger)
	groupSettingRepository := repository.NewGroupSettingRepository(db, logger)
	groupJoinRequestRepository := repository.NewGroupJoinRequestRepository(db, logger)
	groupPinnedMessageRepository := repository.NewGroupPinnedMessageRepository(db, logger)
	groupQRCodeRepository := repository.NewGroupQRCodeRepository(db, logger)
	configRegistry := bc.Registry
	consulRegistry := registry.NewConsulRegistry(configRegistry)
	messageServiceClient := grpc.NewMessageServiceClient(consulRegistry)
	userServiceClient := grpc.NewUserServiceClient(consulRegistry)
	configBroker := data.Broker
	brokerBroker, cleanup2, err := broker.NewBroker(configBroker)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	groupService := service.NewGroupService(groupRepository, groupMemberRepository, groupSettingRepository, groupJoinRequestRepository, groupPinnedMessageRepository, groupQRCodeRepository, messageServiceClient, userServiceClient, brokerBroker, db, logger)
	groupHandler := handler.NewGroupHandler(groupService, logger)
	grpcServer := server.NewGRPCServer(configServer, auth, logger, groupHandler)
	httpServer := server.NewHTTPServer(configServer)
	lifecycle := app.DefaultLifecycle()
	kratosApp := newApp(logger, grpcServer, httpServer, consulRegistry, lifecycle)
	return kratosApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
